'use strict';

angular.module('scalearAngularApp', [
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ui.router',
    'ngTouch',
    // 'ui.bootstrap',
    'ui.bootstrap.datepicker',
    'ui.bootstrap.timepicker',
    // 'ui.bootstrap.tooltip',
    // 'ngAnimate',
    'ui.sortable',
    'ui.calendar',
    'ngDragDrop',
    'infinite-scroll',
    'xeditable',
    'googlechart',
    'pascalprecht.translate',
    'angularMoment',
    'textAngular',
    'highcharts-ng',
    'config',
    'chieffancypants.loadingBar',
    'anguFixedHeaderTable',
    'mm.foundation',
    'dcbImgFallback',
    'ngclipboard',
    'ngTextTruncate',
    'ngDialog',
    'mgo-angular-wizard',
    'angular-medium-editor',
    'smart-table'
])
